### ISSUE TITLE
[マイページ]エラーメッセージに変数が表示される

### ISSUE THREAD

**Issue by yuko-imagawa** [tomohiroorikasa/ecomyu-web#10]
マイページからのプロフィール、ユーザーID変更画面で、エラーメッセージに変数が表示される
例：「{0}が入力されていません」
例：「{0}は{1}文字以下で入力してください」

関連）ユーザー登録も同様

<img width="444" alt="スクリーンショット 2024-01-22 10 38 39" src="https://github.com/ecomyu/ecomyu-web/assets/156774587/babebe04-4d63-4442-b531-6c7c0cc4c7b8">

**Comment by tomohiroorikasa** [comment]
テンプレートの$t（i18n）で発生している。Viteとi18nの兼ね合いで発生するバグ？

**Comment by tomohiroorikasa** [comment]
Developmentでは発生せずにビルドすると発生するのを確認。
やっぱり、テンプレート内のi18n/$tの書き方がダメっぽい。
`{{ $t('errors.required', [$t('fields.myprofile.id')]) }}`

**Comment by tomohiroorikasa** [comment]
vitePluginsの `@intlify/vite-plugin-vue-i18n`  の読み込み時に `runtimeOnly: false` を指定する必要がありました。
https://github.com/quasarframework/quasar/issues/13229
