### ISSUE TITLE
[マイページ]未投稿ユーザーの「いいね」ページが空表示

### ISSUE THREAD

**Issue by yuko-imagawa** [tomohiroorikasa/ecomyu-web#11]
何も投稿していないユーザー（投稿数0）が、他の人の投稿に「いいね」をする
「マイページ」の「いいね」カウントは増えるが、「いいね」した投稿が画面に表示されない

ただし、投稿数が1になると、「いいね」も表示されるようになる

↓対象の画面はここ（内容は、表示されているパターン）

<img width="445" alt="スクリーンショット 2024-01-22 12 35 12" src="https://github.com/ecomyu/ecomyu-web/assets/156774587/6cff0bc8-69c7-4ac8-a772-cedfd74c58ec">

**Comment by tomohiroorikasa** [comment]
修正しました。
