### ISSUE TITLE
[ページタイトル]コメントを選択すると?となる

### ISSUE THREAD

**Issue by yuko-imagawa** [tomohiroorikasa/ecomyu-web#13]
通常の投稿の場合は、ユーザー名、ユーザーID、投稿日時が表示されている

**↓?となっている例**

<img width="577" alt="スクリーンショット 2024-01-22 10 51 00" src="https://github.com/ecomyu/ecomyu-web/assets/156774587/fdda3059-8796-48b0-8370-3e010e38ddfe">

**↓通常時**

<img width="227" alt="スクリーンショット 2024-01-22 12 43 10" src="https://github.com/ecomyu/ecomyu-web/assets/156774587/17d5c193-ccf1-47b1-a9f0-734d27af28c2">

タガタメでも発生している

**Comment by tomohiroorikasa** [comment]
親の投稿をmetaに表示しようとしていたのを選択された投稿を表示するようにしました。
