### ISSUE TITLE
[退会]登録抹消に伴う各種表示の不整合

### ISSUE THREAD

**Issue by yuko-imagawa** [tomohiroorikasa/ecomyu-web#15]
**問題あると思われる表示内容**
[通知]「???さんからコメントいただきました」と表示されている
[マイページ]フォロー/フォロワー件数が減らない
[マイページ]「いいね」した件数が減らない
[投稿]投稿のコメント件数が減らない

**以下、問題ない表示**
[引用]引用している投稿が(削除された投稿)と表示されている
[マイページ]退会したユーザーが、「フォロー/フォロワー」から消えている
[マイページ]退会したユーザーの投稿が、「いいね」から消えている
[投稿]退会したユーザーのコメントが消えている

**Comment by tomohiroorikasa** [comment]
データの削除に関することなのでAPIに移動します。

**Comment by tomohiroorikasa** [comment]
退会処理に表示されるダイアログとその後のページ遷移がおかしかったかもしれないので修正しておきました。
