### ISSUE TITLE
[トップ] ヘッダーがなくなっている(検索機能も消えている)

### ISSUE THREAD

**Issue by ocyoshino** [tomohiroorikasa/ecomyu-web#3]
- トップページのヘッダーが表示されていない。

- ヘッダーの🔍マークを押すと検索バーが出てくるのが正しいが、ヘッダーがなくなっているため検索機能も消えてしまっている

実行環境
Mac, iPhone

**Comment by tomohiroorikasa** [comment]
ecomyu化（tgtmからecomyu）の際に toolbar から抜けてしまってたのが原因です。
