### ISSUE TITLE
[iPhone]フッターのメニューの表示がおかしい 

### ISSUE THREAD

**Issue by ocyoshino** [tomohiroorikasa/ecomyu-web#4]
- iPhone使用時に表示されるフッターの家マーク(トップ)の位置がズレている
(動作は問題なし)

- マイページ、通知ページではフッターが表示されない

- 色が投稿ボタンと同じ色になっている(仕様？)

![IMG_4883](https://github.com/ecomyu/ecomyu-web/assets/147675631/1b473f9a-f3f5-4c40-8354-44ded045eeed)

**Comment by tomohiroorikasa** [comment]
背景色についてはヘッダーがprimary、フッターがsecondaryになるようにしてます。

**Comment by tomohiroorikasa** [comment]
マイページ、通知ページではフッターが表示されないように見えるのは、iPhoneでscreenの高さをうまく取得できていないのが原因でした方法にスワイプすると表れます。別issueで対応します。
