### ISSUE TITLE
[ユーザーページ]「フォロー中」の文字の背景に不要な吹き出しアイコンがある

### ISSUE THREAD

**Issue by yuko-imagawa** [tomohiroorikasa/ecomyu-web#7]
<img width="499" alt="スクリーンショット 2024-01-22 12 18 30" src="https://github.com/ecomyu/ecomyu-web/assets/156774587/82cccb4f-8453-4faa-83dd-356412de6517">

imageなしのため出ている

**Comment by tomohiroorikasa** [comment]
チャット機能用のボタンの消し忘れてでした。
