### ISSUE TITLE
[トップ]タイムライン投稿が２重で表示される

### ISSUE THREAD

**Issue by yuko-imagawa** [tomohiroorikasa/ecomyu-web#8]
リロードするとタイムライン投稿が２重で表示される状態となる
マイページに遷移後、トップに戻ると解消する

5日前の下に5分前の投稿が来ている例）
<img width="394" alt="スクリーンショット 2024-01-22 12 03 27" src="https://github.com/ecomyu/ecomyu-web/assets/156774587/ee9917cd-5238-4184-b9b2-ec2f75da0901">

**Comment by tomohiroorikasa** [comment]
リロードが重複して呼び出された際の処理にバグがあったのを修正。
