### ISSUE TITLE
[ユーザー登録]利用規約・プライバシーポリシーのリンク先が逆

### ISSUE THREAD

**Issue by yuko-imagawa** [tomohiroorikasa/ecomyu-web#9]
誤）
　利用規約：privacy
　プライバシーポリシー：terms
正）
　利用規約：terms
　プライバシーポリシー：privacy
<img width="373" alt="スクリーンショット 2024-01-22 11 15 56" src="https://github.com/ecomyu/ecomyu-web/assets/156774587/336b0e6f-5073-47ce-8986-2119d347faf0">

**Comment by tomohiroorikasa** [comment]
修正しました。
